# Generated by Django 5.0.6 on 2024-07-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("required_age", models.IntegerField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("dlc_count", models.IntegerField(blank=True, null=True)),
                ("about_the_game", models.TextField(blank=True, null=True)),
                ("supported_languages", models.TextField(blank=True, null=True)),
                ("windows", models.BooleanField(default=False)),
                ("mac", models.BooleanField(default=False)),
                ("linux", models.BooleanField(default=False)),
                ("positive", models.IntegerField(blank=True, null=True)),
                ("negative", models.IntegerField(blank=True, null=True)),
                ("score_rank", models.IntegerField(blank=True, null=True)),
                ("developers", models.CharField(blank=True, max_length=255, null=True)),
                ("publishers", models.CharField(blank=True, max_length=255, null=True)),
                ("categories", models.TextField(blank=True, null=True)),
                ("genres", models.TextField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
