# Generated by Django 5.0.6 on 2024-07-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='dlc_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='linux',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='mac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='negative',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='positive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='required_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='supported_languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='windows',
            field=models.BooleanField(default=False),
        ),
    ]
